// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Generates a personalized travel itinerary based on a destination and travel preferences.
 *
 * - generateTravelItinerary - A function that generates a travel itinerary.
 * - GenerateTravelItineraryInput - The input type for the generateTravelItinerary function.
 * - GenerateTravelItineraryOutput - The return type for the generateTravelItinerary function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateTravelItineraryInputSchema = z.object({
  destination: z.string().describe('The destination for the travel itinerary.'),
  preferences: z
    .string()
    .describe(
      'The travel preferences of the user, including interests, budget, and travel style.'
    ),
});

export type GenerateTravelItineraryInput = z.infer<
  typeof GenerateTravelItineraryInputSchema
>;

const GenerateTravelItineraryOutputSchema = z.object({
  itinerary: z
    .string()
    .describe(
      'A detailed daily itinerary as plain text. Each day should have a title (e.g., "Day 1: Arrival and Exploration"), and sections for Morning, Afternoon, and Evening with relevant emojis. Do not use Markdown formatting like bold or italics.'
    ),
});

export type GenerateTravelItineraryOutput = z.infer<
  typeof GenerateTravelItineraryOutputSchema
>;

export async function generateTravelItinerary(
  input: GenerateTravelItineraryInput
): Promise<GenerateTravelItineraryOutput> {
  return generateTravelItineraryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateTravelItineraryPrompt',
  input: {schema: GenerateTravelItineraryInputSchema},
  output: {schema: GenerateTravelItineraryOutputSchema},
  prompt: `You are a passionate and experienced travel blogger creating an exciting, personalized itinerary. Your tone should be enthusiastic, inspiring, and conversational, like sharing insider tips with a friend. Avoid robotic or overly formal language.

Generate a detailed, day-by-day travel itinerary based on the user's destination and preferences.

The response must be plain text. Do not use any Markdown like asterisks for bold or lists.

For each day, provide:
- A clear, exciting title (e.g., "Day 1: Arrival and Ancient Wonders 🏛️").
- Sections for "Morning ☀️", "Afternoon 🏙️", and "Evening 🌙".
- Specific, actionable suggestions for activities, sights, and food. Make it sound like a recommendation, not just a list.
- Keep it engaging and easy to read.

Destination: {{{destination}}}
Preferences: {{{preferences}}}

Let's get this adventure started! Here is your personalized plan:`,
});

const generateTravelItineraryFlow = ai.defineFlow(
  {
    name: 'generateTravelItineraryFlow',
    inputSchema: GenerateTravelItineraryInputSchema,
    outputSchema: GenerateTravelItineraryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
